# *******************************************************************************
# Copyright 2024-2025 Arm Limited and affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *******************************************************************************

name: "Performance AArch64"

on:
  workflow_dispatch:
    inputs:
      onednn_base_hash:
        required: false
        type: string
        description: 'Baseline oneDNN commit'
      onednn_new_hash:
        required: false
        type: string
        description: 'New oneDNN commit'
      acl_base_hash:
        required: false
        type: string
        description: 'Baseline ACL commit'
      acl_new_hash: 
        required: false
        type: string
        description: 'New ACL commit'
      num_threads:
        required: false
        type: string
        description: 'Number of threads to use'
      benchdnn_command:
        required: false
        type: string
        description: 'benchdnn command to run'
        
  workflow_call:
      

#* Stop stale workflows
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-performance
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  build-acl-cache:
    uses: ./.github/workflows/aarch64-acl.yml

  build-and-test-performance:
    needs: build-acl-cache
    strategy:
      matrix:
        config: [
          { name: c7g, label: ah-ubuntu_22_04-c7g_m-100, threading: OMP, toolset: gcc, build: Release, testset: NIGHTLY }
        ]

    name: ${{ matrix.config.name }}, ${{ matrix.config.toolset }}, ${{ matrix.config.threading }}, ${{ matrix.config.build }}
    runs-on: ${{ matrix.config.label }}
    steps:

      - name: Checkout oneDNN
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: oneDNN

      # Note: This will create a github actions cache
      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@56d043d188c3612951d8755da8f4b709ec951ad6 # v3.31.6
        with:
          cmakeVersion: 3.31.0
          ninjaVersion: 1.12.0

      - if: ${{ matrix.config.threading == 'OMP' }}
        name: Install openmp
        run: |
          sudo apt install -y libomp-dev

      - name: Read version file
        id: get-versions
        run: |
          content=`cat ${{ github.workspace }}/oneDNN/.github/automation/aarch64/ci.json`
          content="${content//[$'\t\r\n$ ']}"
          echo "output=$content" >> $GITHUB_OUTPUT

      - name: Install gcc
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update -y
          sudo apt install -y g++-${{ fromJson(steps.get-versions.outputs.output).dependencies.gcc }}

      - name: Install scons
        run: |
          sudo apt-get update -y
          sudo apt-get install -y scons

      - name: setup python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.10'

      - name: Install scipy
        if: ${{ matrix.config.build == 'Release' }}
        run: pip install scipy statistics

      - name: Clone and Build ACL New 
        if: ${{ inputs.acl_new_hash != '' }}
        run: |
          ACL_ACTION=clone ${{ github.workspace }}/oneDNN/.github/automation/aarch64/build_acl.sh
          ACL_ACTION=build ${{ github.workspace }}/oneDNN/.github/automation/aarch64/build_acl.sh
        env:
          ACL_ROOT_DIR: ${{ github.workspace }}/ComputeLibrary_New
          ACL_VERSION: ${{ inputs.acl_new_hash }}
          ACL_BUILD_TYPE: ${{ matrix.config.build }}
          ACL_THREADING: ${{ matrix.config.threading }}

      - name: Clone and Build ACL (nightly fallback)
        if: ${{ inputs.acl_new_hash == '' }}
        run: |
            ACL_ACTION=clone ${{ github.workspace }}/oneDNN/.github/automation/aarch64/build_acl.sh
            ACL_ACTION=build ${{ github.workspace }}/oneDNN/.github/automation/aarch64/build_acl.sh
        env:
          ACL_ROOT_DIR: ${{ github.workspace }}/ComputeLibrary
          ACL_VERSION: ${{ fromJson(steps.get-versions.outputs.output).dependencies.acl }}
          ACL_BUILD_TYPE: ${{ matrix.config.build }}
          ACL_THREADING: ${{ matrix.config.threading }}

      - name: Clone and Build ACL Base
        run: |
          ACL_ACTION=clone ${{ github.workspace }}/oneDNN/.github/automation/aarch64/build_acl.sh
          ACL_ACTION=build ${{ github.workspace }}/oneDNN/.github/automation/aarch64/build_acl.sh
        env:
          ACL_ROOT_DIR: ${{ github.workspace }}/ComputeLibrary_Base
          ACL_VERSION: ${{ inputs.acl_base_hash || fromJson(steps.get-versions.outputs.output).dependencies.acl }}
          ACL_BUILD_TYPE: ${{ matrix.config.build }}
          ACL_THREADING: ${{ matrix.config.threading }}
        

      - name: Get ACL commit hash for cache key
        id: get_acl_commit_hash
        run: |
          if [[ -n "${{ inputs.acl_new_hash }}" ]]; then
            cd "${{ github.workspace }}/ComputeLibrary_New"
          else
            cd "${{ github.workspace }}/ComputeLibrary"
          fi
          echo "ACLCommitHash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set ACL cache path
        id: set_acl_path
        run: |
          if [[ -n "${{ inputs.acl_new_hash }}" ]]; then
            echo "ACL_CACHE_PATH=${{ github.workspace }}/ComputeLibrary_New/build" >> $GITHUB_ENV
          else
            echo "ACL_CACHE_PATH=${{ github.workspace }}/ComputeLibrary/build" >> $GITHUB_ENV
          fi

      - name: Get system name
        id: get_system_name
        run: (echo "SystemName=$(uname)") >> $GITHUB_OUTPUT

      - name: Restore cached ACL
        id: cache-acl-restore
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: ${{ steps.get_system_name.outputs.SystemName }}-acl-${{ matrix.config.toolset }}-${{ matrix.config.build }}-${{ steps.get_acl_commit_hash.outputs.ACLCommitHash }}
          path: ${{ env.ACL_CACHE_PATH }}

      - name: Configure oneDNN  (comparison or nightly)
        run: ${{ github.workspace }}/oneDNN/.github/automation/aarch64/build.sh
        working-directory: ${{ github.workspace }}/oneDNN
        env:
          ACL_ROOT_DIR: ${{ inputs.acl_new_hash != '' && format('{0}/ComputeLibrary_New', github.workspace) || format('{0}/ComputeLibrary', github.workspace) }}
          BUILD_TOOLSET: ${{ matrix.config.toolset }}
          CMAKE_BUILD_TYPE: ${{ matrix.config.build }}
          CMAKE_GENERATOR: Ninja
          GCC_VERSION: ${{ fromJson(steps.get-versions.outputs.output).dependencies.gcc }}
          ONEDNN_ACTION: configure
          ONEDNN_TEST_SET: ${{ matrix.config.testset }}
          ONEDNN_THREADING: ${{ matrix.config.threading }}

      - name: Build oneDNN
        run: ${{ github.workspace }}/oneDNN/.github/automation/aarch64/build.sh
        working-directory: ${{ github.workspace }}/oneDNN
        env:
          ONEDNN_ACTION: build

      - name: Checkout oneDNN base   
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{inputs.onednn_base_hash || fromJson(steps.get-versions.outputs.output).dependencies.onednn-base }}
          path: oneDNN_base

      - name: Checkout oneDNN new
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{inputs.onednn_new_hash || fromJson(steps.get-versions.outputs.output).dependencies.onednn-base }}
          path: oneDNN_new

      - name: Configure oneDNN new
        run: .github/automation/aarch64/build.sh
        working-directory: ${{ github.workspace }}/oneDNN_new
        env:
          ACL_ROOT_DIR: ${{ inputs.acl_new_hash != '' && format('{0}/ComputeLibrary_New', github.workspace) || format('{0}/ComputeLibrary', github.workspace) }}
          BUILD_TOOLSET: ${{ matrix.config.toolset }}
          CMAKE_BUILD_TYPE: ${{ matrix.config.build }}
          CMAKE_GENERATOR: Ninja
          GCC_VERSION: ${{ fromJson(steps.get-versions.outputs.output).dependencies.gcc }}
          ONEDNN_ACTION: configure
          ONEDNN_TEST_SET: ${{ matrix.config.testset }}
          ONEDNN_THREADING: ${{ matrix.config.threading }}

      - name: Build oneDNN new
        run: .github/automation/aarch64/build.sh
        working-directory: ${{ github.workspace }}/oneDNN_new
        env:
          ONEDNN_ACTION: build

      - name: Configure oneDNN base (comparison only or fallback)
        run: .github/automation/aarch64/build.sh
        working-directory: ${{ github.workspace }}/oneDNN_base
        env:
          ACL_ROOT_DIR: ${{ inputs.acl_base_hash != '' && format('{0}/ComputeLibrary_Base', github.workspace) || format('{0}/ComputeLibrary', github.workspace) }}
          BUILD_TOOLSET: ${{ matrix.config.toolset }}
          CMAKE_BUILD_TYPE: ${{ matrix.config.build }}
          CMAKE_GENERATOR: Ninja
          GCC_VERSION: ${{ fromJson(steps.get-versions.outputs.output).dependencies.gcc }}
          ONEDNN_ACTION: configure
          ONEDNN_TEST_SET: ${{ matrix.config.testset }}
          ONEDNN_THREADING: ${{ matrix.config.threading }}

      - name: Build oneDNN base
        run: .github/automation/aarch64/build.sh
        working-directory: ${{ github.workspace }}/oneDNN_base
        env:
          ONEDNN_ACTION: build

      - name: Run performance tests
        shell: bash
        run: |
          OMP_NUM_THREADS=16 bash ${{ github.workspace }}/oneDNN/.github/automation/performance/bench_nightly_performance.sh ${{ github.workspace }}/oneDNN_base/build/tests/benchdnn/benchdnn ${{ github.workspace }}/oneDNN/build/tests/benchdnn/benchdnn base.txt new.txt
        env:
          DYLD_LIBRARY_PATH: ${{ env.ACL_CACHE_PATH }}

      - name: Compare 16 threads performance test results
        run: |
          python ${{ github.workspace }}/oneDNN/.github/automation/performance/benchdnn_comparison.py base.txt new.txt

      - name: Run user-provided benchdnn command on both builds
        if: ${{ inputs.benchdnn_command != '' }}
        shell: bash
        run: |
          echo "Running benchdnn using user-provided command..."
          CMD_ORIG="${{ inputs.benchdnn_command }}"
          PERF="--perf-template=%prb%,%-time%,%-ctime%"
          REPS=3 

          if [[ "$CMD_ORIG" != *"--mode=P"* ]]; then
            echo "Error: command must include --mode=P......."
            exit 1
          fi  
          read -ra TOKENS <<< "$CMD_ORIG"  
          FINAL_ARGS=()

          for tok in "${TOKENS[@]}"; do
            FINAL_ARGS+=( "$tok" )
            if [[ "$tok" == "--mode=P" ]]; then
              FINAL_ARGS+=( "$PERF" )
            fi
          done

          echo "Final arguments: ${FINAL_ARGS[*]}"

          BASE_BINARY="${{ github.workspace }}/oneDNN_base/build/tests/benchdnn/benchdnn"
          NEW_BINARY="${{ github.workspace }}/oneDNN_new/build/tests/benchdnn/benchdnn"

          echo "" > base.txt
          for i in $(seq 1 "$REPS"); do
            echo "Running base iteration $i..."
            OMP_NUM_THREADS=${{ inputs.num_threads || 16 }} "$BASE_BINARY" "${FINAL_ARGS[@]}" >> base.txt
          done

          echo "" > new.txt
          for i in $(seq 1 "$REPS"); do
            echo "Running new iteration $i..."
            OMP_NUM_THREADS=${{ inputs.num_threads || 16 }} "$NEW_BINARY" "${FINAL_ARGS[@]}" >> new.txt
          done

          echo "base.txt"
          cat base.txt || echo "base.txt is empty"
          echo "new.txt"
          cat new.txt || echo "new.txt is empty"

      - name: Print speed comparisons
        if: ${{ inputs.benchdnn_command != '' }}
        run: |
          python3 ${{ github.workspace }}/oneDNN/.github/automation/performance/benchdnn_comparison.py base.txt new.txt

      - name: Check for regressions
        if: ${{ inputs.benchdnn_command == '' }}
        run: |
          python3 ${{ github.workspace }}/oneDNN/.github/automation/performance/benchdnn_comparison.py base.txt new.txt --check

  #* This job adds a check named "Nightly Performance AArch64" that represents overall
  #* workflow status and can be used in branch rulesets
  status:
    needs: build-and-test-performance
    runs-on: ubuntu-latest
    name: "Nightly Performance AArch64"
    steps:
      - name: Print success
        run: echo Success
        
